config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'application#welcome'
  resources :researchers, only: [:new, :create, :show]
  resources :projects do
    resources :texts, only: [:index, :new, :create]
    resources :notes, only: [:index, :new, :create, :edit, :update]
    get 'search', on: :collection
  end
  resources :texts
  resources :notes, only: [:index, :new, :create, :edit, :update] do
    get 'written', on: :collection
  end
  get '/signup', to: 'researchers#new'
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  match '/auth/:provider/callback', to: 'sessions#create_omniauth', via: [:get, :post]
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :researcher
  has_many :notes
  has_many :texts, through: :notes
  has_many :authors, through: :texts
  validates :title, presence: true

  before_destroy :destroy_notes
  scope :search, ->(query) { where("title LIKE ?" , "%#{query}%") }
  def destroy_notes
    self.notes.destroy_all
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_login
  before_action :require_resource_ownership, only: [:edit, :update, :destroy]
  before_action :initialize_project
  def index
    @projects = Project.all
  end

  def new
    initialize_texts
  end

  def create
    @project = current_researcher.projects.build(project_params)
    #move below method back into the action
    attempt_save_project
  end

  def show
  end

  def edit
    
    initialize_texts
  end

  def update
    @project.update(project_params)
    #refactor this, if project.update
    attempt_save_project
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  def search
    @projects = Project.search(params[:search])
    render :index
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :text_ids =>[])
  end

  def initialize_project
    @project = Project.find_by(id: params[:id]) || Project.new
  end

  def initialize_texts
    @texts = Text.all
  end


  def attempt_save_project
    if @project.save
      redirect_to project_path(@project)
    else
      initialize_texts
      params[:id]? (render :edit) : (render :new)
    end
  end
end

app/views/projects/_form.html.erb
<%= form_for project do |f| %>
  <%= f.label :title, value: "Project name" %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br>
  <%= f.label :texts %>
  <br>
  <%= f.collection_check_boxes :text_ids, texts, :id, :title %>
  <br>
  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit <%= @project.title %></h1>
<%= render partial: "application/errors", locals: { model: @project } %>
<%= render partial: "form", locals: { project: @project, texts: @texts } %>
<%= form_tag project_path(@project.id), method: "delete" do %>
  <%= submit_tag "Delete #{@project.title}" %>
<% end %>

app/views/projects/index.html.erb
<h1>List of Projects</h1>
<% @projects.each do |project| %>
  <h3>Name:<%= link_to project.title, project_path(project) %></h3>
  <p>Researcher: <%= link_to project.researcher.name, researcher_path(project.researcher) %></p>
<% end %>
<% if false %>
  <%= form_tag("/projects/search", :method => :get) do %>
    <%= label_tag(:search, "Search projects:") %>
    <%= text_field_tag(:search) %>
    <%= submit_tag("Search") %>
  <% end %>
<% end %>

app/views/projects/new.html.erb
<h1>Create a new project</h1>
<%= render partial: "application/errors", locals: { model: @project } %>
<%= render partial: "form", locals: { project: @project, texts: @texts } %>

app/views/projects/show.html.erb
<h1>Project: <%= @project.title %></h1>
<h3><%= link_to "Edit this project", edit_project_path %></h3>
<h3>Researcher: <%= link_to @project.researcher.name, researcher_path(@project.researcher) %></h3>
<h3>Description</h3>
<p> <%= @project.description %> </p>
<%= link_to "Add a new text", new_project_text_path(@project) %><br>
<%= link_to "Add a new note with text", new_project_note_path(@project) %><br>
<%= link_to "Display all notes for project", project_notes_path(@project) %>
<h3>Texts</h3>
<% @project.texts.uniq.each do |text| %>
  <h3><%= link_to text.title, text_path(text) %></h3>
  <p>by <%= text.author.name %></p>
  <p>Note: <%= text.note(@project).content %></p>
  <%= link_to "edit note", edit_project_note_path(@project, text.note(@project)) %>
  <hr>
<% end %>