config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'application#welcome'
  resources :researchers, only: [:new, :create, :show]
  resources :projects do
    resources :texts, only: [:index, :new, :create]
    resources :notes, only: [:index, :new, :create, :edit, :update]
    get 'search', on: :collection
  end
  resources :texts
  resources :notes, only: [:index, :new, :create, :edit, :update] do
    get 'written', on: :collection
  end
  get '/signup', to: 'researchers#new'
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  match '/auth/:provider/callback', to: 'sessions#create_omniauth', via: [:get, :post]
end

app/models/researcher.rb
class Researcher < ApplicationRecord
  has_many :projects
  has_secure_password
  validates :name, :email, presence: true, uniqueness: true

  # def self.find_or_create_from_auth_hash(auth_hash)
  #   byebug
  #   researcher = self.find_or_create_by(email: auth_hash[:info][:email]) do
  #     researcher.name = auth_hash[:info][:email]
  #   end
  #   researcher
  # end
end

app/controllers/researchers_controller.rb
class ResearchersController < ApplicationController
  before_action :require_login, only: [:show]
  def new
    @researcher = Researcher.new
  end

  def create
    @researcher = Researcher.new(researcher_params)
    if @researcher.save
      login_researcher(@researcher)
    else
      render :new
    end
  end

  def show
    @researcher = Researcher.find_by(id: params[:id])
  end


  private

  def researcher_params
    params.require(:researcher).permit(:name, :email, :institution, :password)
  end

  
end

app/views/researchers/new.html.erb
<%= render partial: "application/errors", locals: { model: @researcher } %>
<%= form_for @researcher do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :institution %>
  <%= f.text_field :institution %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit %>
<% end %>

app/views/researchers/show.html.erb
<h1>Welcome, <%= @researcher.name %>!</h1>
<h2>From <%= @researcher.institution %> </h2>

<h2>Your projects</h2>
<% @researcher.projects.each do |project| %>
  <%= link_to project.title, project_path(project.id) %>
<% end %>
<br>
<%= button_to "Write a new note for a project", new_note_path, method: :get %>