config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'application#welcome'
  resources :researchers, only: [:new, :create, :show]
  resources :projects do
    resources :texts, only: [:index, :new, :create]
    resources :notes, only: [:index, :new, :create, :edit, :update]
    get 'search', on: :collection
  end
  resources :texts
  resources :notes, only: [:index, :new, :create, :edit, :update] do
    get 'written', on: :collection
  end
  get '/signup', to: 'researchers#new'
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  match '/auth/:provider/callback', to: 'sessions#create_omniauth', via: [:get, :post]
end

app/models/text.rb
class Text < ApplicationRecord
  has_many :notes
  belongs_to :author
  belongs_to :religious_tradition
  has_many :projects, through: :notes
  validates :title, presence: true, uniqueness: true
  accepts_nested_attributes_for :author
  accepts_nested_attributes_for :religious_tradition
  # def author_name
  #   self.try(:author).try(:name)
  # end

  # def author_name=(name)
  #   author = Author.find_or_create_by(name: name)
  #   self.author = author
  # end
  def author_attributes=(author)
    
    if author[:name].empty?
      self.author = Author.find_by(id: author[:id])
    else
      author.delete("id")
      self.create_author(author)
    end
  end
 


  def religious_tradition_attributes=(religious_tradition)
    if religious_tradition[:name].empty?
      self.religious_tradition = ReligiousTradition.find_by(id: religious_tradition[:id])
    else
      self.create_religious_tradition(name: religious_tradition[:name])
    end
  end



  def note(project)
    notes.where(project_id: project.id).first
  end
  
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :require_login
  def index
    if params[:project_id]
      initialize_project
      if @project.nil?
        redirect_to projects_path
      else
        @texts = @project.texts
      end
    else
      @texts = Text.all
    end
  end

  def show
    initialize_text
  end

  def new
    if params[:project_id] && !Project.exists?(params[:project_id])
      redirect_to projects_path
    else
      @text = Text.new(project_ids: [params[:project_id]])
      @text.build_author
      @text.build_religious_tradition
      initialize_authors
    end
  end

  def create
    @text = Text.new(text_params)
    if @text.save
      redirect_to text_path(@text)
    else
      initialize_authors
      render :new
    end
  end
  
  def edit
    
      initialize_text
      initialize_authors
    
  end

  def update
    initialize_text
    @text.update(text_params)
    if @text.save
      redirect_to text_path(@text)
    else
      initialize_authors
      render :edit
    end
  end

  def destroy
    initialize_text
    @text.destroy
    flash[:notice] = "Text deleted."
    redirect_to texts_path
  end


  private

  def text_params
    params.require(:text).permit(:title,
      :subject,
      project_ids: [],
      author_attributes: [
        :id,
        :name],
      religious_tradition_attributes: [
        :id,
        :name
      ]
      
    )
  end

  def initialize_text
    @text = Text.find(params[:id])
  end

  def initialize_authors
    @authors = Author.all
    @religious_tradition = ReligiousTradition.all
    initialize_project if params[:project_id]
  end

  def initialize_project
    @project = Project.find_by(id: params[:project_id])
  end
end

app/helpers/texts_helper.rb
module TextsHelper
  def author_id_field(text)
    if text.author_id.nil?
      select_tag "text[author_id]", options_from_collection_for_select(Author.all, :id, :name)
    else
      hidden_field_tag "text[author_id]", text.author_id
    end
  end
end

app/views/texts/_details.html.erb
<h2><%= link_to text.title, text_path(text) %></h2>
<h4>by <%= text.author.name %></h4>
<p>Religious tradition: <%= text.religious_tradition.name %></p>

app/views/texts/_form.html.erb
<%= form_for text do |f| %>
  <%= hidden_field_tag "text[project_ids][]", text.project_ids%>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :subject %>
  <%= f.text_field :subject %>
  <br>
  
  <%= f.fields_for :author do |author| %>
    <%= author.label :id, "Choose an existing author" %>
    <%= author.collection_select :id, authors, :id, :name %><br>
    <%= author.label :name, "Input a new author (will override above)" %>
    <%= author.text_field :name, value: "" %><br>
    
    
  <% end %>
  <%= f.fields_for :religious_tradition do |r| %>
    <%= r.label :id, "Choose a religious tradition" %>
    <%= r.collection_select :id, religious_tradition, :id, :name %><br>
    <%= r.label :name, "Input new religious tradition (will override above)" %>
    <%= r.text_field :name, value: "" %>
  <% end %>
  <br>

  <%= f.submit %>
<% end %>

app/views/texts/edit.html.erb
<%= render partial: "application/errors", locals: { model: @text } %>
<h1>Edit text: <%= @text.title %></h1>
<%= render partial: "form", locals: { text: @text, project: @project, authors: @authors, religious_tradition: @religious_tradition } %>

app/views/texts/index.html.erb
<h1>Texts</h1>
<% @texts.each do |text| %>
  <hr>
  <%= render partial: "details", locals: {text: text} %>
<% end %>

app/views/texts/new.html.erb
<%= render partial: "application/errors", locals: { model: @text } %>
<h1>Enter a new text</h1>
<%= render partial: "form", locals: { text: @text, project: @project, authors: @authors, religious_tradition: @religious_tradition } %>

app/views/texts/show.html.erb
<%= render partial: "details", locals: { text: @text } %>
<p>Description of text: <%= @text.subject %></p>
<h2>notes</h2>
<% @text.notes.each do |note| %>
  <% if note.content %>
    <h3>From the project <%= note.project.title %> </h3>
    <%= note.content  %>
  <% end %>
<% end %>
<%= link_to "Edit text", edit_text_path(@text) %>