config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'application#welcome'
  resources :researchers, only: [:new, :create, :show]
  resources :projects do
    resources :texts, only: [:index, :new, :create]
    resources :notes, only: [:index, :new, :create, :edit, :update]
    get 'search', on: :collection
  end
  resources :texts
  resources :notes, only: [:index, :new, :create, :edit, :update] do
    get 'written', on: :collection
  end
  get '/signup', to: 'researchers#new'
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  match '/auth/:provider/callback', to: 'sessions#create_omniauth', via: [:get, :post]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReligionResearcher</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    

    <%= yield %>
    <hr>
    <% if logged_in? %>
      <%= link_to "Create a new project", new_project_path %> | 
      <%= link_to "View all projects", projects_path %><br>
      <%= link_to "Enter a new text", new_text_path %> | 
      <%= link_to "View all texts", texts_path %><br>
      <%= link_to "Write a new note", new_note_path %> | 
      <%= link_to "View all notes", written_notes_path %><br>
      <%= link_to "View your profile", researcher_path(current_researcher) %> | 
      <%= link_to "Log out", logout_path %>
    <% else %>
      <%= link_to 'Sign up', new_researcher_path %>
      <%= link_to 'Log in', login_path %>
      <%= link_to 'Sign in with Github', '/auth/github', method: :post %>
    <% end %>
  </body>
</html>